### ISSUE TITLE
Error -2 connecting to redis123:6379

### ISSUE THREAD

**Issue by francisco-camargo** [python-engineer/python-docker-tutorial#7]
Hey,

Was following the youtube [video](https://youtu.be/0H2miBK_gAk?si=OxkecQ3Vd20qWoeG) and ran into issues with Redis, I then cloned this repo and ran `docker-compose up` and I get the following when I go to `localhost/hits`. Note; going to `localhost/` works fine. I am on Windows10

```bash
python-server            | INFO:     172.23.0.1:55738 - "GET /hits HTTP/1.1" 500 Internal Server Error
python-server            | ERROR:    Exception in ASGI application
python-server            | Traceback (most recent call last):
python-server            |   File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 264, in connect
python-server            |     sock = self.retry.call_with_retry(
python-server            |   File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
python-server            |     return do()
python-server            |   File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 265, in <lambda>
python-server            |     lambda: self._connect(), lambda error: self.disconnect(error)
python-server            |   File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 595, in _connect
python-server            |     for res in socket.getaddrinfo(
python-server            |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
python-server            |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
python-server            | socket.gaierror: [Errno -2] Name or service not known
python-server            | 
python-server            | During handling of the above exception, another exception occurred:
python-server            | 
python-server            | Traceback (most recent call last):
python-server            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
python-server            |     result = await app(  # type: ignore[func-returns-value]
python-server            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
python-server            |     return await self.app(scope, receive, send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
python-server            |     await super().__call__(scope, receive, send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
python-server            |     await self.middleware_stack(scope, receive, send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
python-server            |     raise exc
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
python-server            |     await self.app(scope, receive, _send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
python-server            |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
python-server            |     raise exc
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
python-server            |     await app(scope, receive, sender)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
python-server            |     await self.middleware_stack(scope, receive, send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
python-server            |     await route.handle(scope, receive, send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
python-server            |     await self.app(scope, receive, send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
python-server            |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
python-server            |     raise exc
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
python-server            |     await app(scope, receive, sender)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
python-server            |     response = await func(request)
python-server            |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
python-server            |     raise e
python-server            |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
python-server            |     raw_response = await run_endpoint_function(
python-server            |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
python-server            |     return await run_in_threadpool(dependant.call, **values)
python-server            |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
python-server            |     return await anyio.to_thread.run_sync(func, *args)
python-server            |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
python-server            |     return await get_async_backend().run_sync_in_worker_thread(
python-server            |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
python-server            |     return await future
python-server            |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
python-server            |     result = context.run(func, *args)
python-server            |   File "/code/src/main.py", line 22, in read_root
python-server            |     r.set("foo", "bar")
python-server            |   File "/usr/local/lib/python3.10/site-packages/redis/commands/core.py", line 2341, in set
python-server            |     return self.execute_command("SET", *pieces, **options)
python-server            |   File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 533, in execute_command
python-server            |     conn = self.connection or pool.get_connection(command_name, **options)
python-server            |   File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 1086, in get_connection
python-server            |     connection.connect()
python-server            |   File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 270, in connect
python-server            |     raise ConnectionError(self._error_message(e))
python-server            | redis.exceptions.ConnectionError: Error -2 connecting to redis123:6379. Name or service not known.
```

I'm new to Docker and not sure how all the ports work, but was hoping cloning this repo directly would work. Everything else on the video so far has worked and the content was fantastic!

**Comment by francisco-camargo** [comment]
Just solved it for both my version of the code and the directly cloned version. 
```python
redis.Redis(host='redis123', port=6379)
```
may not work because `redis123` was not the container name given after running `docker-compose up`. To remedy this, I added a `container_name` field under the `docker-compose.yaml` section for `redis`. I then use the same name within `main.py`
